baseurl         = "https://radu-matei.com"
languageCode    = "en-us"
title           = "radu's blog"
theme           = "kiss"
Paginate        = 5
copyright       = "&copy; <a href=\"https://twitter.com/matei_radu\" rel=\"noreferrer\" target=\"_blank\">Radu Matei</a> 2021"
disqusShortname = "radu-matei"
googleAnalytics = "UA-81142224-1"

[params.info]
    homeTitle = "radu's blog"

[params.rss] # Adding this tag enables RSS feed
    includeContent = true           # Includes whole content in rss
    authorName     = "Radu Matei"   # Author full name
    authorEmail    = "root@radu.sh" # Author email

[params.social]
    github  = "radu-matei"
    rss     = "index.xml"
    about   = "https://radu-matei.com/about"
    twitter = "matei_radu"
    email   = "root@radu.sh"
    #linkedin = ""
    #gitlab = ""
    instagram = "iamradum"
    codepen   = ""
    facebook  = ""

[params.social.config]
    platforms = [ "twitter", "github" ]

[taxonomies]
    tag      = "tags"
    category = "categories"

[params.features]
    disqusOnDemand = false
